// Generated by CoffeeScript 1.7.1
(function() {
  var BOARD_HEIGHT, BOARD_WIDTH, COLORS, TILE_SIZE;

  COLORS = ["#FFFF00", "#FF9900", "#FF0000", "#9900FF", "#0000FF", "#00FF00", "#000000"];

  BOARD_WIDTH = 1200;

  BOARD_HEIGHT = 800;

  TILE_SIZE = 50;

  window.CanvasRenderer = (function() {
    function CanvasRenderer(canvas) {
      this.canvas = canvas;
      this.ctx = this.canvas.getContext('2d');
    }

    CanvasRenderer.prototype.renderTile = function(tile) {
      this.ctx.fillStyle = COLORS[tile.colorIndex];
      return this.ctx.fillRect(tile.x, tile.y, TILE_SIZE, TILE_SIZE);
    };

    CanvasRenderer.prototype.clear = function() {
      return this.ctx.clearRect(0, 0, BOARD_WIDTH, BOARD_HEIGHT);
    };

    return CanvasRenderer;

  })();

}).call(this);
