// Generated by CoffeeScript 1.7.1

/*
	Coffeescript file that controls game logic and canvas rendering
	Written by Connor Taylor
 */


/*										Constants */

(function() {
  var bindKeys, board, gameLoop;

  board = new GameManager;

  bindKeys = function() {
    return $(document).bind('keydown', function(e) {
      switch (e.which) {
        case 32:
          return board.ui.spacePressed = true;
        case 37:
          return board.ui.leftPressed = true;
        case 39:
          return board.ui.rightPressed = true;
        case 40:
          return board.ui.downPressed = true;
      }
    });
  };

  gameLoop = function() {
    board.updatePositions();
    board.spawnTile();
    return board.render();
  };

  $(function() {
    board.render();
    bindKeys();
    return setInterval(gameLoop, 60);
  });

}).call(this);
