// Generated by CoffeeScript 1.7.1
(function() {
  var TILE_SIZE;

  TILE_SIZE = 50;

  window.Tile = (function() {
    function Tile(row, col) {
      this.row = row;
      this.col = col;
      this.x = this.col * TILE_SIZE;
      this.y = this.row * TILE_SIZE;
      this.colorIndex = 0;
      this.hasMoved = false;
      this.userCanMove = false;
      this.neighbors = [null, null, null];
    }

    return Tile;

  })();

}).call(this);
