// Generated by CoffeeScript 1.7.1
(function() {
  window.UserInputLogger = (function() {
    function UserInputLogger() {
      this.leftPressed = false;
      this.rightPressed = false;
      this.downPressed = false;
      this.spacePressed = false;
    }

    return UserInputLogger;

  })();

}).call(this);
